//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jupviec_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DONDOI_NHANGIUPVIEC
    {
        public string MaDD { get; set; }
        public string MaNVGV { get; set; }
        public bool TrangThaiNhan { get; set; }
    
        public virtual DONDOINHANVIEN DONDOINHANVIEN { get; set; }
        public virtual NHANVIENGIUPVIEC NHANVIENGIUPVIEC { get; set; }
    }
}
