//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jupviec_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONDATDICHVU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONDATDICHVU()
        {
            this.CT_NHANGIUPVIEC = new HashSet<CT_NHANGIUPVIEC>();
            this.DONDOINHANVIENs = new HashSet<DONDOINHANVIEN>();
            this.DICHVUDINHKEMs = new HashSet<DICHVUDINHKEM>();
        }
    
        public string MaDon { get; set; }
        public string MaKH { get; set; }
        public string DichVu { get; set; }
        public string DienTich { get; set; }
        public string Voucher { get; set; }
        public string DanhGiaDV { get; set; }
        public string DiaDiemGV { get; set; }
        public int SoLuongNV { get; set; }
        public int TrangThai { get; set; }
        public System.DateTime NgayDonDep { get; set; }
        public System.TimeSpan GioDonDep { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<System.DateTime> NgayTaoDon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_NHANGIUPVIEC> CT_NHANGIUPVIEC { get; set; }
        public virtual DANHGIANHANVIEN DANHGIANHANVIEN { get; set; }
        public virtual DICHVUCHINH DICHVUCHINH { get; set; }
        public virtual DIENTICH DIENTICH1 { get; set; }
        public virtual VOUCHER VOUCHER1 { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONDOINHANVIEN> DONDOINHANVIENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DICHVUDINHKEM> DICHVUDINHKEMs { get; set; }
    }
}
