//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jupviec_api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JupViecDBContex : DbContext
    {
        public JupViecDBContex()
            : base("name=JupViecDBContex")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CT_DONDOI_NHANGIUPVIEC> CT_DONDOI_NHANGIUPVIEC { get; set; }
        public virtual DbSet<CT_NHANGIUPVIEC> CT_NHANGIUPVIEC { get; set; }
        public virtual DbSet<DANHGIANHANVIEN> DANHGIANHANVIENs { get; set; }
        public virtual DbSet<DIACHI> DIACHIs { get; set; }
        public virtual DbSet<DICHVUCHINH> DICHVUCHINHs { get; set; }
        public virtual DbSet<DICHVUDINHKEM> DICHVUDINHKEMs { get; set; }
        public virtual DbSet<DIENTICH> DIENTICHes { get; set; }
        public virtual DbSet<DONDATDICHVU> DONDATDICHVUs { get; set; }
        public virtual DbSet<DONDOINHANVIEN> DONDOINHANVIENs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KYNANG> KYNANGs { get; set; }
        public virtual DbSet<NHANVIENGIUPVIEC> NHANVIENGIUPVIECs { get; set; }
        public virtual DbSet<QUANLY> QUANLies { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<THICHVACHAN> THICHVACHANs { get; set; }
        public virtual DbSet<VOUCHER> VOUCHERs { get; set; }
    }
}
